#!/usr/bin/perl

use Data::Dumper;

use constant {
	# Pacemaker RA standard exit codes
	OCF_SUCCESS => 0,
	OCF_ERR_GENERIC => 1,
	OCF_ERR_ARGS => 2,
	OCF_ERR_UNIMPLEMENTED => 3,
	OCF_ERR_PERM => 4,
	OCF_ERR_INSTALLED => 5,
	OCF_ERR_CONFIGURED => 6,
	OCF_ERR_NOT_RUNNING => 7,
	OCF_RUNNING_MASTER => 8,
	OCF_FAILED_MASTER => 9,
	
	# Internal debugging levels
	LOG_DEBUG => 5,
	LOG_INFO => 4,
	LOG_WARN => 3,
	LOG_CRIT => 2,
	LOG_FATAL => 1,
};

use vars qw { @ARGV %ENV $LOG_LEVEL };

$LOG_LEVEL = 4;

my $log = "/tmp/pxc_resource_agent.log";
open( LOG, ">> $log" ) or die "Could not open logfile: $log\n";

sub print_log {
	my( $string ) = @_;
	my $date = `date`; chop $date;
	print LOG $date . " " . $string;
	close( LOG );
}

sub debug {
	return if $LOG_LEVEL < LOG_DEBUG;
	print_log( @_);
}
sub info {
	return if $LOG_LEVEL < LOG_INFO;
	print_log( @_ );
}

# Main block
eval {
	my $command = $ARGV[0];
	info( "Command: $command\n");
	debug( "ENV: " . Dumper( \%ENV ));
	
};
if( $@ ) {
	exit OFC_ERR_GENERIC;
} else {
	exit OCF_SUCCESS;
}

